### ISSUE TITLE
Korisnik mora ručno unijeti inventurni broj, a prema SRS-u sistem treba generisati jedinstveni inventurni broj

### ISSUE THREAD

**Issue by apuce** [SoftverInzenjeringETFSA/SI2016_TIM11#19]
**Komponenta:** Dodavanje inventurne stavke
**commit ID:** ba685c77af8d0d666116bdf89d9ac130f60bf359
**Opis problema:** Prema SRS-u sistem treba da dodjeljuje jedinstven inventurni broj, a ne da se isti ručno unosi. (FZ 9.3. Sistem dodjeljuje jedinstveni inventurni broj za svaku stavku)
**Koraci za reproduciranje problema:**
1. Pokrenuti web aplikaciju prema uputama.
2. Izabrati tab ‘Inventurne stavke’
3. Kliknuti na dugme ‘Dodaj novu inventurnu stavku’

Inventurni broj je obavezno polje za unijeti i stavka se ne može dodati bez prethodno tačno unesenog inventurnog broja, a očekivano je da sistem generiše jedinstven inventurni broj.

![image](https://cloud.githubusercontent.com/assets/17410215/26763411/d212eb82-4952-11e7-9c1d-48d18e5075e3.png)

**Comment by enafly** [comment]
Ispravljen bug u commit-u: 9a293b0eebd75fbd9dee0f026a0afc248fc695cd
