### ISSUE TITLE
Pojava ciklične veze prilikom izmjene kategorije

### ISSUE THREAD

**Issue by dariopejcinovic** [SoftverInzenjeringETFSA/SI2016_TIM11#20]
**Komponenta**: Izmjena kategorije
**commit ID**: ba685c77af8d0d666116bdf89d9ac130f60bf359
**Opis problema**: Prema SRS-u uslov validnosti kod mijenjanja kategorije (FZ - Izmjena kategorije) parent kategorija ne smije biti kategorija koja se upravo modificira. 
**Koraci za reproduciranje problema**:
1. Pokrenuti web aplikaciju prema uputama.
2. Izabrati tab ‘Kategorije’
3. Kliknuti na dugme za izmjenu kod neke od postojećih kategorija. 
Moguće je odabranoj kategoriji kao nadkategoriju postaviti samu sebe. Klikom na dugme ‘Sačuvaj’ javlja se greška da je uočena ciklična veza, međutim izmjena se ipak spašava, i u svakom narednom kliku na tab ‘Kategorije’ javlja sljedeće:

![git](https://cloud.githubusercontent.com/assets/22944536/26762193/3ce248e6-493e-11e7-8211-b68b5f171d83.jpg)

**Comment by sanilmusic** [comment]
Ispravljeno.
