### ISSUE TITLE
Nedostatak informacija o nemogućnosti prijave na sistem s nevalidnim podacima

### ISSUE THREAD

**Issue by dariopejcinovic** [SoftverInzenjeringETFSA/SI2016_TIM11#21]
**Komponenta**: Prijava na sistem
**commit ID**: ba685c77af8d0d666116bdf89d9ac130f60bf359
**Opis problema**: Prilikom prijave na sistem sa nepostojećim korisničkim imenom se ne prikazuje nikakva poruka o nepostojanju istog. Također, ukoliko se unose nevalidni podaci, ne ispisuje se odgovarajuća poruka. (FZ1)
**Koraci za reproduciranje problema**: 
1. Pokrenuti web aplikaciju prema uputama;
2. Unijeti nevalidne podatke (npr. Korisničko ime sa 2 ili sa 17 karaktera ili lozinka koja sadrži manje od 8 karaktera ili neispravna lozinka za postojeći korisnički račun ili nepostojeće korisničko ime u bazi i slično);
3. Klikom na dugme “Prijavi se”, ne ispisuje se odgovarajuća poruka.

**Comment by mulicvedad** [comment]
Popravljeno.  Hvala Vam što ste ukazali na grešku poštovani g. Pejčinović @DakiPej .
