### ISSUE TITLE
Nije moguće  kreirati korisnički račun čije odgovarajuće korisničko ime ima 4 karaktera

### ISSUE THREAD

**Issue by ajla24** [SoftverInzenjeringETFSA/SI2016_TIM11#22]
**Komponenta**: Kreiranje novog korisničkog računa
commit ID: ba685c77af8d0d666116bdf89d9ac130f60bf359
**Opis** **problema**: Nije moguće  kreirati korisnički račun čije odgovarajuće korisničko ime ima 4 karaktera (FZ3)
**Koraci za reproduciranje problema:** 
Pokrenuti web aplikaciju prema uputama
Prijaviti se na sistem s administratorskim privilegijama
Odabrati tab “Korisnici”
Odabir opcije za kreiranje novog korisničkog računa (“dodaj novog korisnika”)
Unijeti nevalidne podatke za korisničko ime (“username”), npr “daki”
Unijeti validne podatke za ostala neispunjena polja
Sačuvati izmjene (klikom na dugme “sačuvaj”)

**Comment by amra16947** [comment]
Ispravljeno.
