### ISSUE TITLE
Korisnik logovan kao audit team, ima opciju za brisanje invenura

### ISSUE THREAD

**Issue by ajla24** [SoftverInzenjeringETFSA/SI2016_TIM11#23]
**Komponenta:** Brisanje inventura od strane osoba koje vrše inventuru
commit ID: ba685c77af8d0d666116bdf89d9ac130f60bf359
**Opis problema:** Korisnik logovan kao audit team, ima opciju za brisanje invenura.
**Koraci za reproduciranje problema:** 
1. Pokrenuti web aplikaciju prema uputama.
2. Logovati se sa rolom audit team.
3. Odabrati tab ‘Inventure’.
Očekivano je da osobe koje vrše inventuru nemaju mogućnost brisanja istih, nego da je to omogućeno samo administratorima.

**Comment by mulicvedad** [comment]
Nesuglasice sa SRS-om su riješene.
