### ISSUE TITLE
Prilikom izmjene informacija inventurne stavke, moguće je stavci dodijeliti već postojeći inventurni broj

### ISSUE THREAD

**Issue by muhamedparic** [SoftverInzenjeringETFSA/SI2016_TIM11#24]
**Komponenta:** Izmjena inventurne stavke
**Commit ID:** ba685c7
**Opis problema:** Prilikom izmjene informacija inventurne stavke, moguće je stavci dodijeliti već postojeći inventurni broj.
**Koraci za reproduciranje problema:** 

1. Pokrenuti web aplikaciju prema uputama
2. Prijaviti se na sistem s administratorskim privilegijama
3. Odabrati tab “Inventurne stavke”
4. Odabrati opciju za izmjenu inventurne stavke (pretpostavka da u bazi postoje 2 inventurne stavke)
5. Izmijeniti podatke o inventurnom broju odabrane stavke (dodijeliti već postojeći inventurni broj)
6. Spasiti izmjene 

![pasted image 0](https://cloud.githubusercontent.com/assets/17408083/26764258/02aec32c-4964-11e7-8db5-6a855b362521.png)

**Comment by enafly** [comment]
Ispravljen bug u commit-u: 9a293b0eebd75fbd9dee0f026a0afc248fc695cd
