### ISSUE TITLE
Nije moguće kreirati inventuru bez odabira prostorije

### ISSUE THREAD

**Issue by muhamedparic** [SoftverInzenjeringETFSA/SI2016_TIM11#25]
**Komponenta:** Kreiranje nove inventure
**Commit ID:** ba685c77af8d0d666116bdf89d9ac130f60bf359
**Opis problema:** Nije moguće kreirati inventuru bez odabira prostorije (FZ19)
**Koraci za reproduciranje problema:** 

1. Pokrenuti web aplikaciju prema uputama
2. Prijaviti se na sistem s administratorskim privilegijama ili s privilegijama korisnika koji ima mgućnost kreiranja nove inventure
3. Odabir opcije za kreiranje nove inventure
4. Unos validnog naziva 
5. Spremiti izmjene

![pasted image 0](https://cloud.githubusercontent.com/assets/17408083/26764284/4c618900-4964-11e7-9350-f3738208b4ac.png)

**Comment by sanilmusic** [comment]
Neophodne promjene strukture baze podataka.
