### ISSUE TITLE
Ukoliko se briše tip lokacije, a postoji odgovarajuća lokacija s navedenim tipom lokacije, pored što će se obrisati sam tip lokacije, obrisat će se i sama lokacija

### ISSUE THREAD

**Issue by muhamedparic** [SoftverInzenjeringETFSA/SI2016_TIM11#26]
**Komponenta:** Brisanje tipa lokacije
**Opis problema:** Ukoliko se briše tip lokacije, a postoji odgovarajuća lokacija s navedenim tipom lokacije, pored što će se obrisati sam tip lokacije, obrisat će se i sama lokacija
**Koraci za reproduciranje problema:** 

1. Pokrenuti web aplikaciju prema uputama
2. Prijaviti se na sistem s administratorskim privilegijama
3. Dodati dva tipa lokacije (zgradu i ucionicu)
4. Dodati dvije lokacije (hacijenda tipa zgrade i SH-1 tipa ucionice čija nadlokacija je hacijenda)
5. Obrisati tip lokacije “ucionica”

![pasted image 0](https://cloud.githubusercontent.com/assets/17408083/26764297/a309a788-4964-11e7-9601-a09053a1d36d.png)
![pasted image 0 1](https://cloud.githubusercontent.com/assets/17408083/26764301/bd50d77e-4964-11e7-8641-54a51ce35443.png)
![pasted image 0 2](https://cloud.githubusercontent.com/assets/17408083/26764302/c234bbac-4964-11e7-9e2f-ea78f7919cdf.png)
![pasted image 0 3](https://cloud.githubusercontent.com/assets/17408083/26764304/c63bcb0a-4964-11e7-9c01-a9c34f909337.png)

**Comment by sanilmusic** [comment]
Ispravljeno.
