### ISSUE TITLE
Otpis inventurne stavke

### ISSUE THREAD

**Issue by liliumdev** [SoftverInzenjeringETFSA/SI2016_TIM11#27]
**Komponenta**: Otpis inventurne stavke
**Commit ID**: ba685c77af8d0d666116bdf89d9ac130f60bf359
**Opis problema**: Nije implementiran opis inventurne stavke. 
**Koraci za reproduciranje problema**:

1. Pokrenuti web aplikaciju prema uputama
2. Logovati se sa rolom administratora
3. Nije implementiran opis inventurne stavke

**Comment by sanilmusic** [comment]
Zahtjeva promjene strukture baze podataka.
