### ISSUE TITLE
Izmjena korisnika dopušta puno više od onoga što treba.

### ISSUE THREAD

**Issue by ramicbenjamin** [SoftverInzenjeringETFSA/SI2016_TIM11#28]
Komponenta: Update korisnika.
commit ID: ba685c77af8d0d666116bdf89d9ac130f60bf359
Opis problema: Update korisnika bi trebao dopustiti samo da se rola izmijeni, međutim, priliko odabira opcije izmjene, prikažu se opcije za izmjenu svih atributa korisnika.
Koraci za reproduciranje problema:
1.Pokrenuti web aplikaciju prema uputama
2.Logovati se sa rolom administraotra
3.Otvoriti stranicu korisnika
4.Kliknuti na opciju izmjene korisnika
5.Trebalo bi da se prikaže opcija samo za izmjenu role, međutim prikažu se sva polja za izmjenu.

**Comment by amra16947** [comment]
Ispravljeno.
